// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjqspEA_7OLo8VNMzaMV7Nmvi933G6uQQ',
    appId: '1:167331457100:android:87da6c1718edb77d40ece9',
    messagingSenderId: '167331457100',
    projectId: 'keepnotesclone-48de0',
    storageBucket: 'keepnotesclone-48de0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAav9vuKsrzOsBIpNzRP0FYFSjWNRL7XRc',
    appId: '1:167331457100:ios:b3a98c84b22f5f9140ece9',
    messagingSenderId: '167331457100',
    projectId: 'keepnotesclone-48de0',
    storageBucket: 'keepnotesclone-48de0.firebasestorage.app',
    iosClientId: '167331457100-qkec0rpmrnrtiupktlagbin6ndcg7thm.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleKeepNotesClone',
  );
}
