// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfX9ApDsGIKNdPy3AesHzq4aouquHVG0',
    appId: '1:779259636759:android:0bb03a9f1669b9abbfc052',
    messagingSenderId: '779259636759',
    projectId: 'keep-notes-clone-4f486',
    storageBucket: 'keep-notes-clone-4f486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpPX4X_XKdidknwvKstHLN6kyr1XBA27U',
    appId: '1:779259636759:ios:3eb0341f0497dacbbfc052',
    messagingSenderId: '779259636759',
    projectId: 'keep-notes-clone-4f486',
    storageBucket: 'keep-notes-clone-4f486.firebasestorage.app',
    iosBundleId: 'com.example.googleKeepNotesClone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ9_WPgcNo4F607sx-FUeByfeFK0hLd2o',
    appId: '1:779259636759:web:1ba720051655ad85bfc052',
    messagingSenderId: '779259636759',
    projectId: 'keep-notes-clone-4f486',
    authDomain: 'keep-notes-clone-4f486.firebaseapp.com',
    storageBucket: 'keep-notes-clone-4f486.firebasestorage.app',
    measurementId: 'G-22KWHSQ50T',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ9_WPgcNo4F607sx-FUeByfeFK0hLd2o',
    appId: '1:779259636759:web:c76205ffd36988e7bfc052',
    messagingSenderId: '779259636759',
    projectId: 'keep-notes-clone-4f486',
    authDomain: 'keep-notes-clone-4f486.firebaseapp.com',
    storageBucket: 'keep-notes-clone-4f486.firebasestorage.app',
    measurementId: 'G-JF4J74F3TG',
  );

}